COMP: Fix "‘itksys_stl’ does not name a type" compile error.
This updates code to be independent of KWSys function signature changes
introduced in InsightSoftwareConsortium/ITK@d584693 (ENH: Remove use of
include <itksys/stl/*> and itksys_stl::*) following Slicer r24836 (ENH:
Update ITKv4 to v4.9.0 release branch)

It fixes the following build errors:

/home/jcfr/Projects/SlicerCIP/Loadable/ParticlesDisplay/Logic/vtkSlicerParticlesDisplayLogic.cxx:135:11: error: ‘itksys_stl’ does not name a type
     const itksys_stl::string fname(filename);
           ^
/home/jcfr/Projects/SlicerCIP/Loadable/ParticlesDisplay/Logic/vtkSlicerParticlesDisplayLogic.cxx:136:5: error: ‘itksys_stl’ has not been declared
     itksys_stl::string name = itksys::SystemTools::GetFilenameWithoutExtension(fname);
     ^
/home/jcfr/Projects/SlicerCIP/Loadable/ParticlesDisplay/Logic/vtkSlicerParticlesDisplayLogic.cxx:137:68: error: ‘name’ was not declared in this scope
     std::string uname( this->GetMRMLScene()->GetUniqueNameByString(name.c_str()));
                                                                    ^